### ISSUE TITLE
Hard XOR clause violated

### ISSUE THREAD

**Issue by vuphan314** [meelgroup/gaussmaxhs#2]
Hi @msoos,

GaussMaxHS appears to violate a hard clause:
```
cat f.wcnf
```
```
p wcnf 3 1 4
x 4 1 2 3 0
```

Output:
```
gaussmaxhs f.wcnf -verb=0
```
```
c MaxHS 3.0.0
xor added to vec:[ 1 2 3 ] (3)
c Solved by Init Bnds.
o 0
s OPTIMUM FOUND
v -1 -2 -3
```

This may be related to issue #1.

Thank you.

**Comment by msoos** [comment]
Oh, damn. The `-DONLY_TOPLEVEL` was enabled in the source code somehow. That caused issues. This has now been fixed. It should be a LOT faster now. Wow, that was a big bug :( Sorry!

**Comment by msoos** [comment]
Thanks a lot for catching this!
